### PR TITLE
Update adal5-http.service.ts to fix bug for Http service

### PR DESCRIPTION
**Pull request by subhankar99**

### CODE REVIEW

**Comment by vivekdtiwari** [comment]
Hey. Just wanted to share a point. <br/>
Changing method from _this.http.request(method,url,options)_ to _this.http.request(url,options)_ will not be enough. This will always result in a GET request based on implementation in http.js of Angular<br/>
If however the method call is changed to _this.http\[method\](url,options)_ this works perfectly for all types of request (GET,POST,..)

**Comment by EddWills95** [comment]
Just run into this issue myself 
Cheers for the suggestion @vivekdtiwari 
👍

**Comment by subhankar99** [comment]
Can you please fix this ASAP. I am actively using this library for my project

**Comment by subhankar99** [comment]
@grumar can you please update the NPM package as well?

**Comment by grumar** [comment]
@subhankar99 of course, new package published.

**Pull request merged**
